version: '3'

services:
    frontend:
        build: ./front-end
        container_name: bgmagik_frontend
        restart: always
        ports:
            - "5000:5000"
               
    backend:
        build: ./back-end
        container_name: bgmagik_backend
        environment: 
            MONGO_HOST: mongo
            MONGO_DATABASE: bgmagik
        ports:
            - "8080:8080"
        links:
            - mongo
    mongo:
        container_name: bgmagik_mongo
        image: mongo
        ports:
            - "27018:27017"